### ISSUE TITLE
Preview is incomplete

### ISSUE THREAD

**Issue by Arignir** [raven-os/website#17]
The rich preview of https://raven-os.org is incomplete.

A rich preview is the preview shown in social medias when someone is sending a link to a website.

We can use [richpreview.org](https://richpreview.com/?url=https%3A%2F%2Fraven-os.org) to test the output. This website reports a couple of errors that we should (all) take seriously.

**Comment by person-m** [comment]
https://github.com/raven-os/website/commit/b4fbac2ce3661997255e24cfcb2986c62569b611
For richpreview.org, everything is fine.
We need to change og:image with our URL. Actually it's an url to our github logo.

**Comment by person-m** [comment]
https://github.com/raven-os/website/commit/bdf78803ae80a2e73f2e16dc26b78c2180532773
Updated og:image with our URL
