### ISSUE TITLE
File name should be in lowercase

### ISSUE THREAD

**Issue by Arignir** [raven-os/website#20]
We're on Linux, file name with starting with an uppercase letter is a pain in the ass to access from a terminal.

**Comment by AlexErling** [comment]
Hello, I can help, just let me know what you need me to do!

**Comment by Arignir** [comment]
Hello, 

Everything is in the description: all filenames should be in lowercase.

Thank you for your interest in Raven-OS.

**Comment by person-m** [comment]
https://github.com/raven-os/website/commit/bdf78803ae80a2e73f2e16dc26b78c2180532773
Renamed some files in PascaleCase to snake_case
